server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-password: 123456
    key-store-type: JKS
    key-alias: selfsigned
    key-store-provider: SUN
spring:
  social:
    facebook:
      app-id: 433437670446420
      app-secret: 6363b469eab96f6eef6e61a9284f4d39
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/social
    username: root
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
security:
  require-ssl: true